version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    links:
      - db
  db:
    image: mongo
    container_name: db
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
volumes:
  db-data: